### ISSUE TITLE
本家のフォロー

### ISSUE THREAD

**Issue by kinichiro** [kicad-jp/kicad-doc#21]
翻訳の皆さん、こんにちは。
本家で、adocのセクション指定変更と、
eeschemaの画像リニューアルが行われました。
この取り込みをしませんか？
PRを出した方が良いでしょうか？

**Comment by yoneken** [comment]
@kinichiro さん
お疲れさまです。本家での議論、ずっと見てました。 https://github.com/ciampix/kicad-doc/issues/84
本家はフォローしないと、ビルドが壊れてしまって取り込んでもらえなくなるので急務の課題です。
私は帰宅したら作業できますけれど、もし急ぎでしたらPRください。よろしくお願いします。

**Comment by kinichiro** [comment]
@yoneken さん、私も帰宅してからなので、九時過ぎになると思います。

**Comment by kinichiro** [comment]
@yoneken さん、すみませんが本家のフォロー作業をお願いできますでしょうか。

私も帰宅して九時過ぎになるので、と書きたかったのですが先走りました。

よろしくお願いいたします。

**Comment by yoneken** [comment]
了解です！
やっておきます♪

**Comment by yoneken** [comment]
https://github.com/kicad-jp/kicad-doc/commit/c0d146b7fffc839f26e38dff3b138b33199c9b84 で対応しました．

**Comment by kinichiro** [comment]
@yoneken さん、ありがとうございました :-)
