### ISSUE TITLE
Wikiページの誤リンク

### ISSUE THREAD

**Issue by starfort-jp** [kicad-jp/kicad-doc#24]
Wikiページ”現在の翻訳ステータス”のFile、CvPcb が Eeschema にリンクされてしまっています。
また、本日のjapanese po files のアップデートに対応しましたので米倉さんへメールしました。
あわせてご確認をお願いします。

**Comment by kinichiro** [comment]
@starfort-jp さん、WikiのCvPcbのFileのリンクを直しておきました。

**Comment by starfort-jp** [comment]
@kinichiro さん、修正ありがとうございました。
