### ISSUE TITLE
図や画像に関する課題

### ISSUE THREAD

**Issue by starfort-jp** [kicad-jp/kicad-doc#26]
＜＜07/23/2015 現在＞＞
note : 
1)画像のIssueを分離して独立(07/23/2015)、以下は図／画像に関するIssueと思われるもの
//---

＜全般＞
- [ ] ----：キャプチャ画像にユーザー名が残っている

＜Eeschema＞ proofreading : correcting typos.
- [ ]  268：原文の図（image:images/2000000800003E6E0000154B2A71537E.png[2000000800003E6E0000154B2A71537E_png]）が適当でない。（縦方向の位置に差がない）
- [ ]  335：図（image:images/ja/status_bar.png[]）にズーム倍率が入っていない。(より左側の"Z 1.00"のような部分で見切れている)
- [ ]  470：図（image:images/wires_labels.png[Wires labels]）が古いバージョンのソフト（右メニューが違う）
- [ ]  484：図（image:images/ja/sch_with_buses.png[Example schematic with buses]）が古いバージョンのソフト（右メニューが違う）、PCAという説明文の名前と一致していない。
- [ ]  651：図（image:images/ja/file_menu.png[File menu]）がkicadから起動した制限付きのメニューになっている。（単独で起動が必要）
- [ ]  953：原文のアイコン（image:images/icons/hierarchy_nav.png[icons/hierarchy_nav_png]）が正しくない。（これは上部メニューバーのもの）
- [ ]  973：PDFで何故かこの図が974の後にもう一度挿入されている。
- [ ] 1006：PDFで下にある図が上の図と同じ。

＜Pcbnew＞ proofreading : correcting typos.
- [ ]  752：画像（image:images/ja/100000000000007A0000002651F79CA5.png[100000000000007A0000002651F79CA5_png]）と文字が被っている
- [ ]  753：画像（image:images/100000000000007A00000026D48F1971.png[100000000000007A00000026D48F1971_png]）と文字が被っている
- [ ]  767：PDFで図の位置が文の後ろ。（配置見直し要）
- [ ]  853：画像(image:images/ja/2000000900003094000008CA41334F3B.png[2000000900003094000008CA41334F3B_png])が枠からはみ出て文字に重なっている。
- [ ]  854：画像(image:images/ja/10000000000001B20000014F8449F983.png[10000000000001B20000014F8449F983_png])が枠からはみ出て文字に重なっている。
- [ ]  855：画像(image:images/10000000000000FF000000A989993852.png[10000000000000FF000000A989993852_png])が枠からはみ出て文字に重なっている。
- [ ]  856：画像(image:images/1000000000000114000000B804ED21E4.png[1000000000000114000000B804ED21E4_png])が枠からはみ出て文字に重なっている。
- [ ]  857：画像(image:images/100000000000010C000000B26BA7AD80.png[100000000000010C000000B26BA7AD80_png])が枠からはみ出て文字に重なっている。
- [ ] 1143：PDFで下に図がない（図は次頁にある、逆に上の図は前頁の末にあるべき）
## GerbView

2015年７月２８日追加(nosuz)
- [ ] 個々のアイコンを説明する部分のアイコンが最新ではないものがある。多分これまでの版のアイコン画像ではないか？　上流で修正する必要がある。

**Comment by kinichiro** [comment]
本家の方で画像についてのディスカッションissueが起こされました。 https://github.com/ciampix/kicad-doc/issues/132

**Comment by kinichiro** [comment]
表の中のスクリーンショットがはみ出ているのをなんとかできないかと調べました。

[AUTHORS_README.adoc](https://github.com/kicad-jp/kicad-doc/blob/japanese/src/AUTHORS_README.adoc)にスクリーンショットは書式をパラメータ設定するというのが書かれてるのを見つけて、それを試してみました。
すると、`image::images/abc.png[scaledwidth=50%]` とかできるのが分かりました。
ただこの :: のブロック形式マクロは表の中では効かないようでした。
表の中だと、`image:images/abc.png[width=50%]` とインライン形式マクロならOKでした。

また、画像を含む表の中の文字が下に偏ってしまう問題もあり、これは表のオプション指定で、
`valign="middle"` とすることで真ん中に表示させることができることが分かりました。
`valign="top"` はやってみましたが効きませんでした。これはバグかもしれないです。

この2点を試しにPl_Editorに施してみました。
- 本家のPR https://github.com/ciampix/kicad-doc/pull/138
- 適用したPl_EditorのPDF http://ci.kicad-pcb.org/job/kicad-doc-testing-pull-request/125/artifact/build-cmake/src/Pl_Editor/en/Pl_Editor.pdf

本家でこの方法が公認されるか確認するつもりのPRなので、マージされたらこの方法で調整していけばよいのではないかと考えてます。

残念なのはEPUB形式はこの2点を施してもガチャガチャなことです。
http://ci.kicad-pcb.org/job/kicad-doc-testing-pull-request/125/artifact/build-cmake/src/Pl_Editor/en/Pl_Editor.epub
