### ISSUE TITLE
PDF上のレイアウトに関する課題

### ISSUE THREAD

**Issue by starfort-jp** [kicad-jp/kicad-doc#27]
＜＜07/23/2015 現在＞＞
note : 
1)PDFレイアウトのIssueを分離して独立(07/23/2015)、以下はPDF上のレイアウトに関するIssueと思われるもの
//---

＜全般＞
- [ ] ----：キャプチャ画像にユーザー名が残っている

＜CvPcb＞ proofreading : correcting typos.
- [ ]  218：PDFで表の文字が重なっている

＜Eeschema＞ proofreading : correcting typos.
- [ ] 全般：PDFで強調 _ foo _ が効いていない。
- [ ]  974：PDFで”注”なのに項目になってしまっている。
- [ ]  255：PDFで項目になっていない。（254と同様に項目とすべき））
- [ ]  256：PDFで項目になっていない。（254と同様に項目とすべき））
- [ ]  264：PDFで項目になっていない。（263と同様に項目とすべき））
- [ ]  265：PDFで項目になっていない。（263と同様に項目とすべき））
- [ ]  311：PDFで下に未訳部分と思われる原文が挿入されている。（poファイルにはない部分、2.3節のすべて）
- [ ]  312：PDFで本行の前に位置すべき2.4節のタイトルが原文のまま。（poファイルにはない）
- [ ]  372：PDFで次のページが空白。
- [ ]  373：PDFで表になっているが、説明文が図の最下端から始まっている。
- [ ]  374：PDFで最後の項目がページからはみ出して表示されていない。
- [ ]  410：PDFで画像が枠からはみ出て文字に重なっている。
- [ ]  412：PDFで画像が枠からはみ出て文字に重なっている。
- [ ]  492-495：PDFで各行が項目になっていないため見ずらい。
- [ ]  671：PDFで冒頭に" 1. "が付いている。（続く5664, 5673の２行とともに項目"・"とすべき）
- [ ]  677：PDFで次のページが空白。
- [ ]  943：PDFで項目になっていない。（上の２行と同様に項目とすべき））
- [ ]  973：PDFで何故かこの図が974の後にもう一度挿入されている。
- [ ]  999：PDFで" \* "が先頭についている。（poファイルにはない）
- [ ] 1006：PDFで下にある図が上の図と同じ。
- [ ] 1033：PDFで" \* "が先頭についている。（poファイルにはない）
- [ ] 1040：PDFのレイアウトがおかしい
- [ ] 1137：PDFで項目になっていない。（1136と同様に項目とすべき））
- [ ] 1138：PDFで項目になっていない。（1136と同様に項目とすべき）

＜Pcbnew＞ proofreading : correcting typos.
- [ ]    7：PDFで" \* "が両端に入っている。
- [ ]   93：PDFで何故かこの行の前にNoteが置かれて別扱いになっている。
- [ ]  105：PDFで項目になっていない。（104と同様に項目とすべき））
- [ ]  106：PDFで項目になっていない。（104と同様に項目とすべき））
- [ ]  349：PDFで" \* "が先頭についている。（poファイルにはない、項目とすべき）
- [ ]  350：PDFで" \* "が先頭についている。（poファイルにはない、次行とともに項目とすべき0
- [ ]  638：PDFで" *\* "が意味不明（強調でも水平線でもない。PDFで" *\* "と表示されている）
- [ ]  657：PDFで" \* "が両端に入っている。（強調表示されていない）
- [ ]  669：PDFで下に図がない。（次ページにある。レイアウト見直し要）
- [ ]  678：PDFで下に図がない。（次ページにある。レイアウト見直し要）
- [ ]  687：PDFで" *\* "が意味不明（強調でも水平線でもない）
- [ ]  693：PDFで" *\* "が意味不明（強調でも水平線でもない）
- [ ]  694：PDFで" *\* "が意味不明（強調でも水平線でもない）
- [ ]  695：PDFで" \* "が両端に入っている。（5375,5386の項目にはない。アンバランス）
- [ ]  713：PDFで" *\* "が意味不明（強調でも水平線でもない）、PDFで下の行と違って項目になっていない（項目とすべき）
- [ ]  716-721：PDFで項目になっていない。（715と同様に項目とすべき））
- [ ]  725：PDFで下に未訳部分と思われる原文が図で挿入されている。（poファイルにはない部分）
- [ ]  767：PDFで図の位置が文の後ろ。（配置見直し要）
- [ ]  778：PDFで" \* "が先頭についている。（poファイルにはない、前行のコロンの後とともに項目とすべき）
- [ ]  807：PDFで" \* "が先頭についている。（poファイルにはない、次行とともに項目とすべき）
- [ ]  879：PDFで項目になっていない。（878と同様に項目とすべき））
- [ ]  954：PDFで下に未訳部分と思われる原文が挿入されている。（poファイルは挿入されている原文を邦訳すみ）
- [ ] 1172：PDFでOptionsの項目が表示されていない（poファイルにはあり）
- [ ] 1180：PDFで" *\* "が意味不明（強調でも水平線でもない）
- [ ] 1181：PDFで" *\* "が意味不明（強調でも水平線でもない。一か所だけPDFで" *\* "が表示されている）

＜Pl_Editor＞ proofreading : correcting typos.
- [ ]   14-21：PDFでこのセクションが章になっていない

//---
## KiCad

２０１５年７月２８日追加(nosuz)
- [ ] KiCad.adoc:182 _kicad.pro_ が反映されない。
- [ ] KiCad.adoc:240  ${KISYSMOD}/connect.pretty が表示されない。 日本語版を$\{KISYSMOD\}と修正してみた。オリジナルも修正の必要ありかも。
- [ ] **なんとか**が反映されていない。反映されているけど見分けがつかない？
  - KiCad.adoc:131 ライブラリ・フォルダ
  - KiCad.adoc:208 フットプリント・ライブラリ・テーブル
  - KiCad.adoc:264 現在のプロジェクトの絶対パスが
  - KiCad.adoc:267 _現在のプロジェクトフォルダ内_
- [ ] _なんとか_が反映されない。反映されているけど見分けがつかない？
  - KiCad.adoc:153 フットプリントを変更
  - KiCad.adoc:131 フットプリント・ライブラリ・テーブル
  - KiCad.adoc:229 環境変数
  - etc.
- [ ] "_日本語_\n"が反映されない。\nの前に空白？
  - KiCad.adoc:189 "_デフォルトファイルの _kicad.pro_ は、Eeschemaがロードするライブラリファイルのリストを設定するなど必要であれば自由に変更できます。_\n"
  - KiCad.adoc:14 "_著作権_\n"
  - etc.
- [ ] KiCad.adoc:417 アイコンと文章の配置が綺麗でない。

**Comment by kinichiro** [comment]
@starfort_jp さん
課題の分類ありがとうございます。
対策の見通しが立てやすくなりました。
私は翻訳は置いておいて、
リストの項目が項目にならない問題や、
注記がおかしな所等、adocを直さないと
どうにもならない問題の対応を本家で
行います。

**Comment by starfort-jp** [comment]
@kinichiro さん、
まだ7/23付の最新版PDFと照合していないので、既に直っている箇所や新たな問題があるかも知れません。
状況にあわせて適宜内容を変更していって頂ければ幸いです。
厄介な問題ばかりですが、よろしくお願いします。

**Comment by kinichiro** [comment]
@starfort-jp さん
まずはリストの項目が項目になっていないとか *\* がそのまま出力される問題に取り組んでます。
本家でPR https://github.com/ciampix/kicad-doc/pull/126 を出しまして、テストはPASSした状況です。
http://ci.kicad-pcb.org/job/kicad-doc-testing-pull-request/115/artifact/build-cmake/src/ から
変更後の結果のHTMLやPDFを参照できますが、このPRでリスト項目関係は解消されると思っています。

**Comment by starfort-jp** [comment]
@kinichiro さん、
ざっと見た感じですが、ちゃんとリスト項目になってますね。
全てＯＫであれば、かなりの項目が消去されます。素晴らしい！！
かなり読みやすくなるので、PDF上のレイアウト問題の解消を期待しています！

**Comment by nosuz** [comment]
## KiCad

- [ ] KiCad.adoc:182 _kicad.pro_ が反映されない。
- [ ] KiCad.adoc:240  ${KISYSMOD}/connect.pretty が表示されない。 日本語版を$\\{KISYSMOD\\}と修正してみた。オリジナルも修正の必要ありかも。

- [ ] **なんとか**が反映されていない。反映されているけど見分けがつかない？
 * KiCad.adoc:131 ライブラリ・フォルダ
 * KiCad.adoc:208 フットプリント・ライブラリ・テーブル
 * KiCad.adoc:264 現在のプロジェクトの絶対パスが
 * KiCad.adoc:267 _現在のプロジェクトフォルダ内_
- [ ] _なんとか_が反映されない。反映されているけど見分けがつかない？
 * KiCad.adoc:153 フットプリントを変更
 * KiCad.adoc:131 フットプリント・ライブラリ・テーブル
 * KiCad.adoc:229 環境変数
 * etc.
- [ ] "*日本語*\n"が反映されない。\nの前に空白？
 * KiCad.adoc:189 "*デフォルトファイルの _kicad.pro_ は、Eeschemaがロードするライブラリファイルのリストを設定するなど必要であれば自由に変更できます。*\n"
 * KiCad.adoc:14 "*著作権*\n"
 * etc.
- [ ] KiCad.adoc:417 アイコンと文章の配置が綺麗でない。
