### ISSUE TITLE
原文に起因する課題

### ISSUE THREAD

**Issue by starfort-jp** [kicad-jp/kicad-doc#28]
＜＜07/19/2015 現在＞＞
note : 
1)原文のIssueを分離して独立（日本語訳では修正済）
//---
## ＜Eeschema＞ proofreading : all done.
- [ ] 全般：原文に"pop-up menu"と"context menu"が混在している。（日本語訳PR5で"コンテキストメニュー"に統一）
- [x]   ~~27：原文が旧表記のまま("Design rules check (DRC)") （日本語訳PR5で"エレクトリック・ルール・チェッカ (ERC)"へ変更済）~~
- [ ]   41：原文("Common printing commands")が意味不明。（日本語訳PR5で"出図（回路図のプロット）"へ変更済）
- [x]   ~~46：原文記載のアイコン（image:images/icons/plot_hpg.png）が現行ソフトにない。~~
- [ ]   62-65：原文の記述が現行ソフトに合わない。
- [x]   ~~67：原文記載のアイコン（image:images/icons/plot_ps.png[icons/plot_ps_png]）が現行ソフトにない。~~
- [x]   ~~72：原文記載のアイコン（image:images/icons/plot_svg.png[icons/plot_svg_png]）が現行ソフトにない。~~
- [x]   ~~75：原文記載のアイコン（image:images/icons/plot_svg.png[icons/plot_svg_png]）が現行ソフトにない。以下にPDFフォーマットの説明がない。（現行ソフトは指定できる。）~~
- [ ]  169-174：文書中における位置がおかしい。678-699と統合すべき
- [ ]  210：以降にダイアログ・オプション（アノテーションの番号、ダイアログ）の説明がない。
- [ ]  268：原文の図（image:images/2000000800003E6E0000154B2A71537E.png[2000000800003E6E0000154B2A71537E_png]）が適当でない。（縦方向の位置に差がない）
- [ ]  312：原文が旧表記のまま("library manager") （日本語訳PR5で"コンポーネント・ライブラリ・エディタ"へ変更済）
- [x]  ~~348：原文に " a|\n " がある。（このため以降3054行まで位置ずれ、日本語訳PR2で削除）~~
- [ ]  353：原文説明文がおかしい(Copy last selected element or block in the current sheet.)）（日本語訳PR2で正しいものへ差替え済）
- [x]  ~~457：原文"Dotted lines"は、ソフトのメニューでは"Graphic lines or polygons"へ変更されている。（日本語訳PR4で”図形ラインかポリゴン”へ訂正済）~~ →画面に合わせてPolylineに修正
- [ ]  464：原文"their connection pins"と纏められているが、次の５つの説明がない。”バス - バスエントリ”、”階層のラベル”、”インポートされた階層ピン”、”階層ピン”、”ビットマップイメージ”
- [x]  ~~522：原文が"No Connection symbols"のままで"No Connection flag"になっていない。（日本語訳PR4は"フラグ"へ変更済）~~
- [x]  ~~524：原文が"No Connection symbols"のままで"No Connection flag"になっていない。（日本語訳PR4は"フラグ"へ変更済）~~
- [x]  ~~595：原文誤記"EES chema"（日本語訳PR1で"Eeschema"へ変更済）~~
- [ ]  811：原文の記述が正しくない。(If you chose to duplicate the current component, you will be prompted for a new component name.、求められない)
- [x]  ~~936：右のツールバーからは階層ナビゲータを呼び出せない。（原文誤り）~~
- [ ]  952：原文の記述が正しくない。（"choose to enter into sheet."←できない）
- [x]  ~~953：原文のアイコン（image:images/icons/hierarchy_nav.png[icons/hierarchy_nav_png]）が正しくない。（これは上部メニューバーのもの）~~
- [ ]  954：原文の記述が正しくない。（"Click on a sheet name"←できない）
- [x]  ~~955：原文の誤記("main sheet") （日本語訳PR4は"ルート"へ変更済）~~
- [ ]  957：原文"Properties"が意味不明
- [x]  ~~994：原文の誤記("Not Specified") （日本語訳PR4は"パッシブ"へ変更済）~~
## ＜Pcbnew＞ proofreading : all done.
- [x] ~~全般："ModEdit"はもうない。（現在の名称は"PCB footprint editor"）~~
- [ ] 全般：原文に"pop-up menu"と"context menu"が混在している。（日本語訳PR5で"コンテキストメニュー"に統一）
- [x]   ~~20：原文誤り"Alt-U"。（日本語訳PR4で”Ctrl-U”へ訂正済）~~
- [ ]   52：原文の説明が正しくない。（日本語訳PR4は現行ソフトにあわせて修正済）
- [ ]   64：原文の説明が正しくない。（日本語訳PR4は現行ソフトにあわせて修正済）
- [ ]   71：原文の説明が正しくない。（日本語訳PR4は現行ソフトにあわせて修正済）
- [x]   ~~72：原文の図（image:images/ja/Pcbnew_unlock_footprint_option.png[]）が正しくない。（違う部分を赤枠で囲んでいる）~~
- [x]  ~~232：次の図がない。（原文：following figure）~~
- [x]  ~~249：”孤立したパッドやネット”の部分がない。~~
- [x]  ~~257：原文：Move New Modulesがメニューにない。（正しくは：Automatically Place New Footprints）~~
- [x]  ~~258：原文：Move All Modulesがメニューにない。（正しくは：Automatically Place All Footprints）~~
- [x]  ~~338：原文"Via type"はダイアログに無い。（日本語訳PR4で”ビアオプション”へ訂正済）~~
- [x]  ~~340：原文"Minimum clearance"はダイアログに無い。~~
- [ ]  353：原文"This dialog"は前後に無い。
- [x]  ~~526：原文に記述されているオプション"Use Proper Gerber  Extensions"が現行ソフトにない。~~
- [x]  ~~557：原文の説明が正しくない（This text also serves as the module reference, which will be replaced by the final reference on the printed circuit board (U1, IC3, etc.)）~~
- [x]  ~~564：原文誤り（reference field）~~
- [x]  ~~607-610：原文のレイヤ数が古いまま。~~
- [x]  ~~616：原文誤り"Layers Setup"は"Preferences"にない。（日本語訳PR4で”デザインルール”へ訂正済）~~
- [x]  ~~618：原文の最大レイヤ数が１６のまま。~~
- [ ]  697-701：原文で単語（action/effect/operation）が統一されていない（同じ単語に同じ訳語を当てることは適当ではない）
- [x]  ~~734：原文誤り"image:images/Inch mm combo icon.png[]"（日本語訳PR5で”image:images/Inch_mm_combo_icon.png[]”へ訂正済）~~
- [x]  ~~742：メニューバー上には印刷、プロットはない。（ファイルメニューにある、原文：The top menu bar provides access to the files (loading and saving), configuration options, printing, plotting and the help files.）~~
- [x]  ~~761：原文が"module libraries"のまま（日本語訳PR2で"フットプリントライブラリ"へ変更済）~~
- [x]  ~~779-781：トップメニューバーに”3Dモデル表示メニュー”はない（このセクションは削除すべき）~~
- [x]  ~~787：原文の表レイアウト見直し要（アイコン２つが表にない）／原文が"module editor (Modedit) "のまま（日本語訳PR2で"フットプリントエディタ"へ変更済）／原文がweb router FreeRouteのまま~~
- [x]  ~~797：原文auto_track_widthの説明文が正しくない（原文Keepout are areas with no tracks, or/and vias or/and copper areas）（日本語訳PR2で正しいものへ差替え済）~~
- [x]  ~~802：原文sketch modeの意味不明（日本語訳PR2ではアウトラインモード）~~
- [x] ~~1023：原文の説明が正しくない（This text also serves as the module reference, which is ultimately replaced by the real reference (U1, IC3...).）~~
- [x] ~~1031：原文誤り（reference）~~
- [x] ~~1166：原文誤記"Tpically"~~

//---
## KiCad

２０１５年７月２８日追加(nosuz)
- [x] ~~KiCad.adoc:106 the schematic library listは、the component library list。日本語版修正済み~~
- [x] ~~KiCad.adoc:527  a template's icon on the leftは、leftでなくはtopの間違い。日本語版を修正。~~

**Comment by nosuz** [comment]
## KiCad

- [ ] KiCad.adoc:106 the schematic library listは、the component library list。日本語版修正済み
- [ ] KiCad.adoc:527  a template's icon on the leftは、leftでなくtopの間違い。日本語版を修正。

**Comment by kinichiro** [comment]
Eeschema と Pcbnew に関しての原文に起因する課題を本家の方に issue として上げました。
- Eeschema : issue https://github.com/ciampix/kicad-doc/issues/133
- Pcbnew : issue https://github.com/ciampix/kicad-doc/issues/137
  PDFを見ながら実際の画面を動かしてみて、章番号で伝えるようにしました。
  自分で伝えきれると思えた所だけのissueになってしまってます、すいません。

**Comment by starfort-jp** [comment]
@kinichiro さん、
原文対応、ありがとうございます。
翻訳で未対応の部分が修正されたら、その他の課題とあわせて日本語対応していきます。

**Comment by nosuz** [comment]
Issueの提出ありがとうございました。どちらもドキュメントのボリュームが大きいので見てくだけでも大変だったのではないでしょうか。

**Comment by kinichiro** [comment]
分量は多かったですが、@starfort-jp さんの書き出された内容の追認でしたので。
issueとして上げてみましたが、本家も人手不足とのこと。
直してPRしてよ、と返って来るんじゃないかとも思ってます。

**Comment by kinichiro** [comment]
本家の https://github.com/ciampix/kicad-doc/pulls の 142 のPRで、pcbnewのイントロに変更が入ってます。getting started in KiCad にも入ってます。上に挙げられてる項目に関しての修正はないと思います。

**Comment by nickoe** [comment]
Refferenced to here from https://github.com/KiCad/kicad-doc/issues/133, can you tell me if this issue is something you want to resolve for the next release. I am sorry that I don't understand your jibberish here, but I see you listed a lot of tasks.

**Comment by kinichiro** [comment]
@nickoe yes, we expect to resolve this for the next release.
These list items are not for japanese translation problem.
These listed the problem that should be corrected in original English .adoc.

To fix these, many modifications are needed, 
and I thought that just PR these will lead the confusing.

Then I posted as issue https://github.com/KiCad/kicad-doc/issues/133 (for eeschema) and https://github.com/KiCad/kicad-doc/issues/137 (for pcbnew).
These 2 issues are translated version of this issue.

So, could you check https://github.com/KiCad/kicad-doc/issues/133 and https://github.com/KiCad/kicad-doc/issues/137, please ?

Thanks.

**Comment by kinichiro** [comment]
本家側で原文修正のPRを出して修正できたものにチェックを入れて取り消し線で消しました。
（PR出したらチェックをつけて、マージされたら取り消し線で消していました）
残っている項目は私がどう直せばよいかわからなかったものです。
また番号も現状とは合わなくなってきてるようで、問題の箇所をポイントできていないかもしれません。

**Comment by starfort-jp** [comment]
@kinichiro さん、どうもありがとうございます。
大量の修正、おつかれさまでした。m(__)m
もはや現状とは番号が合っていないので、追いかけるだけでも大変ですよね…
ご参考までに、残っているもので照合できたものを列挙しておきます。
//---
１）新しいフットプリントの名前の付け方の変更によるもの
（現状、以前の"reference" fieldから"Footprint Name in Library" fieldへと変更されている）
上記、564,1031　＞　今のID番号、49、413
２）上のフィールド変更にともなうもの
（カッコ内の例が"U"とか"IC"では、"reference"なので不適切。）
上記、567,1023　＞　今のID番号、42、405
３）明らかな誤記
（メニューの説明になってない。自動配線幅なのにキープアウトの説明。）
上記、797　＞　今のID番号、1098
４）項目が変わってページが変わっており、"This dialog"が分かりにくい
（特に修正しなくても問題なさそうですが…）
上記、353　＞　今のID番号、563
５）既に修正された、あるいは修正不要
上記、742,761
//---

**Comment by kinichiro** [comment]
@starfort-jp さん、確認ありがとうございます。
以下のように対応してPR（本家の182）を上げました。
１）49なし、413修正
２）42なし、405修正
３）ボタンのツールチップの文章を使って修正しました。

１）と２）ですが、新規フットプリント作成の節が重複していたのを
13章にまとめたことで、修正箇所が１つずつなしになってます。
４）はすいません、放置しました :-)

また @nosuz さんに上げていただいていたKiCadの2箇所も前回のPR
で修正してました。既に修正済みになってますのでチェック入れて
取り消し線つけておきました。

**Comment by starfort-jp** [comment]
@kinichiro さん、ご対応ありがとうございます。
これで原文に起因する課題もFixですね。
PDFのレイアウト、図や画像のIssueも既に今のドキュメントと乖離しているので、今回のPRが反映され次第、これらのIssueをCloseしようと思います。
