### ISSUE TITLE
RC1でのプログラムとドキュメントの相違

### ISSUE THREAD

**Issue by starfort-jp** [kicad-jp/kicad-doc#48]
とりあえず、2か所見つけました。
初めて使う時に混乱するので、下記のように対応したいと思いますが、如何でしょうか？

＜相違箇所＞
1) Footprint Library Wizard と Footprint Wizard
　Script ベースの Footprint Wizard が追加され、従来の Footprint Wizard が Footprint Library Wizard に名称変更されています。Pcbnewの原文は修正されていますが、既訳部分が古いままです。
また、CvPcbではFootprint Library Table Wizardと呼ばれています。
2) Freerouter
　既にWeb Baseではないのに、ドキュメントやGUIの一部に ”Web” 表記が残っています。
また、名称がFreeroute / FreeROUTE / Freerouting 等となっていて統一されていません。
（Javaのプロジェクト名がFreeRouting、プログラム名はFreerouterです）

＜日本語訳での対応＞
1) Footprint Library Wizard と Footprint Wizard
Pcbnew -> 原文に合わせ、"フットプリント ライブラリ ウィザード"へ変更
CvPcb ->  "フットプリント・ライブラリ・テーブルでの ウィザード"へ変更
　　　　（ライブラリ一覧に"ウィザードを使用して追加"とあるので準拠します）
2) Freerouter
Pcbnew, GUIでの表記を Freerouter へ統一。
"Web"は原文にあっても割愛。

**Comment by yoneken** [comment]
おぉ．素晴らしいです．
私は100%同意です．

**Comment by kinichiro** [comment]
私もその案に賛成です。

**Comment by starfort-jp** [comment]
@yoneken さん、@kinichiro さん、コメントありがとうございます。
さっそく変更を行いました。
また、CvPcbは該当部の画像も表記が古かったので、RC1のものをキャプチャしました。
変更したものを @yoneken さんへメールしましたので、ご確認、宜しくお願いします。

**Comment by yoneken** [comment]
取り急ぎ，starfortさんからいただいた更新をマージしました．
しかし，生成されたPDF https://github.com/kicad-jp/kicad-doc/wiki を見てみると，cvpcbとpcbnewでいくつか英文に戻ってしまっている部分がありますね・・

**Comment by starfort-jp** [comment]
@yoneken さん、更新どうもありがとうございます。
poファイル上では全て翻訳済なんですが、poファイルが古いせいでしょうか？
Windowsではpo4aが使えないので、確認できず申し訳ないです…orz

**Comment by kinichiro** [comment]
@yoneken さん、 @starfort-jp さん、
本家の方で adoc を 4.0リリースに向けて
手直し掛けてしまってる影響かもしれませんね。
お知らせ出来ていなくてすみません。
二つほど未取り込みのPRもありまして、
また他の人も更新をするかも知れず、
もう少し本家側での更新があるかもしれません。

**Comment by starfort-jp** [comment]
@kinichiro さん、情報ありがとうございます。
Pcbnewは未だ更新がありそうですね。
poファイルが更新されましたら、対応致します。
