### ISSUE TITLE
2015/10/21版 原文の問題点

### ISSUE THREAD

**Issue by starfort-jp** [kicad-jp/kicad-doc#57]
### １.Pcbnew（ID番号だとズレることがあるので、原文ー邦訳を列挙していきます）

Set the coordinates origin for the photo plot and drill files, one must place the auxiliary axis on this origin. Activate the icon image:images/icons/pcb_offset.png[]. Move the auxiliary axis by right-clicking on the chosen location.
フォトプロッタやドリル穴あけ機のための原点座標を設定し、この原点に補助軸を合わせなければなりません。アイコン image:images/icons/pcb_offset.png[] を選択して有効化します。配置したい座標で左クリックすることで補助軸を移動させます。

For each layer, Pcbnew generates a separate file following the GERBER 274X standard, by default in 3.4 format (each coordinate in the file is represented by 7 digits, of which 3 are before the decimal point and 4 follow it), units in inches, and a scale of 1.
Pcbnew はデフォルトで 4.6 フォーマット（整数 4 桁、小数点以下 6 桁の最大合計 10 桁で示される mm 単位の座標値）による GERBER 274X 標準に準拠したファイルをレイヤごとに生成します。これらは常にスケール 1（等倍）の値となります。

xxxx.copper.pho for the copper side.
xxxx-F_Cu.gtl（表面導体パターン、リフロー面）。
～
xxxx.maskcu.pho for the copper-side solder mask.
xxxx-B_Mask.gbs（裏面レジストマスク）。

The format used by Pcbnew is RS274X format 3.4, Imperial, Leading zero omitted, Abs format. These are very usual settings.
Pcbnew で利用されるフォーマットは、ゼロサプレス（先方、後方ゼロ省略）、絶対値表記の RS274X 4.5/4.6 (mm) フォーマットです。

| Use Protel filename extensions
| Use .gbl .gtl instead of .pho for file name extensions.
| Protel の拡張子を使用する
| .gbr の代わりに .gbl .gtl  .gbs .gts  .gbp .gtp  .gbo .gto 拡張子を使用します。

Copper layers are the usual working layers used by the automatic router to place and re-arrange tracks. Layer 1 is the copper (solder) layer. Layer 32 is the component layer. Other layers are the inner layers, from L2 to L31.
導体レイヤ（ .Cu ）は、自動／手動配線および再調整（ rearrange ）で使用される通常の作業レイヤです。0番目のレイヤは表面レイヤ（ F、両面基板でリフロー面、片面基板で部品面 ）です。31番目のレイヤは裏面レイヤ（ B ，両面基板でフロー面、片面基板でディップ面）です。他のレイヤ、In1〜In30は内部レイヤ（ 内層 In1～30 ）です。

Options for footprint exchange:
フットプリントの変更のオプション:

One must choose a new footprint name and use:
新しいフットプリントの名前を入力し、以下のオプションのいずれかを選択します:

_Change Footprint_ for the current footprint
_フットプリント 'xx' の変更_ ：リファレンス 'xx' のフットプリントのみ変更。

_Change same footprints_ for all footprints like the current footprint.
_フットプリント 'yy' の変更_ ：フットプリント名 'yy' のフットプリントを変更。

_Change same footprint+value_ for all footprints like the current
footprint, restricted to components which have the same value.
_同じ定数を持つフットプリントを変更_ ：現在のフットプリントと同じ定数を持つコンポーネントを全て変更。

_Change all_ reloads all footprints on board.
_基板上の全てのフットプリントを再読み込み_ ：基板上にあるフットプリントを全て読み込み直します。

Hold down the middle mouse button and draw a rectangle to zoom to the described area.
マウス中央ボタンを押したままで四角形を描くと、その領域をズームインします。
＞Windows10ではズームしない。

`Delete`: deletes a footprin or a track. (_Available only if the Footprint tool or the track tool is active_)
`Delete(Del)`：フットプリントや配線を削除します。（ _フットプリント モードまたは配線 モードが有効な場合のみ実行可能です。_

The image below shows the footprint library table editing dialog which can be opened by invoking the "Library Tables" entry from the "Preferences" menu.
下の図は、フットプリント・ライブラリ・テーブル編集 (PCB ライブラリ一覧) ダイアログです。上部メニューバーにある “設定” → “ライブラリ テーブルの管理”と辿ると表示できます。

|Use Proper Gerber Extensions
|GERBER format specific.
When creating files, use specific extensions foe each file.
If disabled the Gerber file extension is .pho.
|Exclude pcb edge layer
|GERBER format specific.
Do not plot graphic items on edge layer.
|Print Sheet Ref
|Trace sheet outline and the cartridge.
|Print Pads on Silkscreen
|Enables/disables printing of pad outlines on the silkscreen layers (if the pads have already been declared to appear on these layers). Prevents any pads from being printed in the disabled mode.
|Print Footprint Value
|Enables printing of VALUE text on the silkscreen.
|Print Footprint Reference
|Enables printing of the REFERENCE text on the silkscreen.
|Print other footprint texts
|Enables the printing of other text fields on the silkscreen.
|Force Print Invisible Texts
|Forces printing of fields (reference, value) declared as invisible. In combination with Print Footprint Reference and Print Footprint Value, this option enables production of documents for guiding wiring and repair. These options have proven necessary for circuits using components that are too small (SMD) to allow readable placement of two separate text fields.
|全てのレイヤにシートリファレンスを出力
|シート外形と図枠を出力します。
|シルクスクリーンにパッドを出力
|シルクスクリーンにパッド外形を出力するかどうかの設定を行います(パッドは既に別レイヤで定義されている必要があります)。実際には、無効設定とすることで、全てのパッドを印刷させないようにする場合に役立ちます。
|フットプリントの定数をプロット
|シルク上に定数のテキストを出力します。
|フットプリントのリファレンスをプロット
|シルク上にリファレンスのテキストを出力します。
|非表示の定数/リファレンスを強制的にプロット
|非表示にしているフィールド(リファレンス、定数)を強制的に印刷します。フットプリントのリファレンスと定数の組み合わせにより、ケーブル接続や修理用の製造書類を作成することが出来ます。これらのオプションは非常に小さい部品を使う際にそれぞれの文字フィールドを読みやすく離して配置するために必要です。
|ビアにテンティングしない
|ビア上のハンダマスクを削除します。
|基板外形レイヤのデータを他のレイヤから除外
|基板外形レイヤのデータを他の全てのレイヤから削除します。（ガーバーフォーマットのみ）
|Protel の拡張子を使用する
|ガーバーフォーマットに関する設定。.gbr の代わりに .gbl .gtl  .gbs .gts  .gbp .gtp  .gbo .gto 拡張子を使用します。

The router behavior be configured by pressing _E_ or selecting _Routing Options_ from the context menu. It opens a window like the one below:
ルーターは、配線モードで配線中に _E_ を押すか、コンテキストメニューから _配線オプション_ を選ぶことで設定できます。次のようなウィンドウが開きます。:
### 2. getting_started_in_kicad

Chapter 7 ... As for _.lib_ files, _.kicad_mod_ library files are text files that can contain anything from one to several parts.
_.lib_ と同様に、 _.kicad_mod_ ファイルはテキストファイルで、一つのフットプリントを含むことができます。
### 3. GerbView

文書中で使われているアイコンが全般的に現在のソフトのものと違う

**Comment by kinichiro** [comment]
151021版以降の本家側での修正で、
pcbnewの項目の中ボタンドラッグズームがwin10で効かない件以外は直しました。
これはrc2でも効かないままなのでしょうか？
GSiKは直せてません。
Gerbviewはアイコンを最新化しました。

**Comment by starfort-jp** [comment]
@kinichiro さん、修正ありがとうございます。
中ボタンドラッグズームですが、RC2でも変わりません。Windowsでは元々３ボタンマウスを想定していないので、OSの標準設定ではなくドライバ依存となるのが原因かと思います。KiCad側の問題ではないので、直ることはなさそうです。

**Comment by kinichiro** [comment]
１．と３．については済で、２．は持ち越しとしてクローズします。
