### ISSUE TITLE
EeschemaとPcbnewのビルドが英語になる

### ISSUE THREAD

**Issue by yoneken** [kicad-jp/kicad-doc#9]
5edd7a482c241c5c7bc81fd3a3f922d4c37979a0 で発生しています．原因究明中．
ご迷惑をおかけします．

**Comment by kinichiro** [comment]
Cmakeでhtmlのみ指定、jaのみ指定、
でやってみても化けませんでしたが、
問題はpdfでしょうか？

Pdfをビルドできる環境に出来てなくて
確認できませんでした。

猪口

**Comment by kinichiro** [comment]
以下のコマンドを実行して、ja.poをリフレッシュしてから、

<pre>
# cd src/Eeschema
# touch *.adoc
# ./make.sh po/ja.po
</pre>

cmake のbuild をすると日本語のPDFが出来るようになるのを発見しました。

**Comment by yoneken** [comment]
@kinichiro さん，
ありがとうございます！教えていただいたコマンドで，日本語になることを確認し， 87b570e180fad1614572ddae4e755edbd8400239 で反映させました♪
WIkiのプレビューも更新しておきました．

この過程で，PcbnewのほうにFuzzyが10と未翻訳が1できてしまったので，どなたかに対応いただけると幸いです．

**Comment by kinichiro** [comment]
解決できて良かったです。

`ja.po` が対応する `.adoc` とずれていると、`po4a`コマンドが上手く動かず、
中身が英語のままの `-ja.adoc` を出力してしまうようですね。

できるだけ最新の `.adoc` で `./make.sh` した (= `po4a-updatepo`した) `ja.po` で作業
するのがトラブルを避けられるのかなと思います。
